fix all the things arround db relation

diff --git a/charms/precise/drupal/hooks/db-relation-changed b/charms/precise/drupal/hooks/db-relation-changed
--- a/charms/precise/drupal/hooks/db-relation-changed
+++ b/charms/precise/drupal/hooks/db-relation-changed
@@ -2,11 +2,9 @@
 
 set -eu
 
-juju-log "We've got a db"
-
 source inc/common
 
-if [ -f "$config_file_path" ] && [ -f "$config_db_file_path" ]; then
+if [ -f "$config_db_file_path" ]; then
   juju-log "Drupal is already setup, just silently going away"
   exit 0
 fi
@@ -17,35 +15,41 @@ user=`relation-get user`
 password=`relation-get password`
 
 if [ -z "$database" ]; then
+  juju-log "The database couldn't be created."
   exit 0
 fi
 
-# Drupal: Include the new Settings.
-echo -e "\ninclude 'settings.db.php';" >> $config_file_path
-
-# Database info.
+# Drupal: Fill with the db relation info.
 cp files/charm/drupal/settings.db.php $config_db_file_path
-
 sed -i "s/\${host}/$host/" $config_db_file_path
 sed -i "s/\${database}/$database/" $config_db_file_path
 sed -i "s/\${user}/$user/" $config_db_file_path
 sed -i "s/\${password}/$password/" $config_db_file_path
 
-# Configuring the Salt hash.
+# Install or configure the database.
 (
   cd $drupal_path
   
-  if is_drupal_booting; then  
-    drupal_hash_salt=`drush php-eval "echo drupal_get_hash_salt();"`
-  else
-    drupal_hash_salt=`drush php-eval "echo drupal_random_key();"`
+  # If needed create the local settings file.
+  if [ ! -f $config_local_file_path ]; then
+    echo "<?php" > $config_local_file_path
   fi
+
+  # Fresh install.
+  if ! is_drupal_configurated; then
+    # Install Drupal, hell yeah!!
+    drush site-install -y standard --db-url=mysql://$user:$password@$host/$database --site-name="$SITE_NAME" --account-name="$ADMIN_USERNAME" --account-pass="$ADMIN_PASSWORD" --account-mail="$ADMIN_EMAIL" --clean-url=1
+
+    # Include the local settings.
+    echo -e "\ninclude 'settings.local.php';" >> $config_file_path
+  fi
+
+  # Include the db info into local settings.
+  echo -e "\ninclude 'settings.db.php';" >> $config_local_file_path
 )
-sed -i "s/^\$drupal_hash_salt = \'\'\;/\$drupal_hash_salt = \'$drupal_hash_salt\'\;/" $config_file_path
 
 juju-log "Resetting permissions"
-chmod 0644 $config_file_path
-chmod 0644 $config_db_file_path
+chmod 0644 $drupal_path/sites/default/settings*.php
 chown -R ubuntu:www-data $project_path
 
 # When project is from an existent Git repository, will try to import the dump form the branch.
